"""Code extracted from the prior implementation, kept close to its source.

``pipeline.py`` is generated by ``extract.py`` from the notebook in the pinned clone, so
the transcription is checkable rather than trusted. Nothing here is edited by hand.
"""
